#使用nacos配置中心配置
spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000           # 过期时间
      #      key-prefix: CACHE_              # key前缀
      use-key-prefix: true            # 是否使用写入redis前缀
      cache-null-values: true         # 是否允许缓存空值
  thymeleaf:
    cache: false
  session:
    store-type: redis
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.110.20:8333
  zipkin:
    base-url: http://192.168.110.20:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.110.20:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: gulimall-product
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.110.20:8848
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 10000

logging:
  level:
    com.tim.gulimall: debug
feign:
  sentinel:
    enabled: true
