spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.110.20:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.110.20:8333
  redis:
    host: 192.168.110.20
    port: 6379
  session:
    store-type: redis

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


server:
  port: 20000
  servlet:
    session:
      timeout: 30m

logging:
  level:
    com.tim.gulimall: debug