#使用nacos配置中心配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.110.20
    port: 6379
  session:
    store-type: redis
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.110.20:8848
  elasticsearch:
    rest:
      uris: 192.168.110.20:9200
server:
  port: 12000

logging:
  level:
    com.tim.gulimall: debug
