spring:
  redis:
    host: 192.168.110.20
    port: 6379
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.110.20:8848
  session:
    store-type: redis
server:
  port: 40000

logging:
  level:
    com.tim.gulimall: debug

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10