#使用nacos配置中心配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    addresses: 192.168.110.20
    port: 5672
    virtual-host: /
    # 开启发送端确认
    publisher-confirms: true
    # 开启发送端消息抵达队列的确认
    publisher-returns: true
    # 只要抵达队列，以异步发送优先回调我们这个returnconfirm
    template:
      mandatory: true
    # 手动ack消息
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.110.20:8333

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.110.20:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.110.20:8848
#  application:
#    name: gulimall-ware
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 11000